### ISSUE TITLE
Documentation for ark_ed_on_bls12_381 incorrectly refers to BLS12-377

### ISSUE THREAD

**Issue by daira** [arkworks-rs/curves#93] opened 2022-01-01 00:23 UTC
## Summary of Bug

https://docs.rs/ark-ed-on-bls12-381/latest/ark_ed_on_bls12_381/ says:
> This library implements a twisted Edwards curve whose base field is the scalar field of the curve BLS12-377.

That's incorrect; it should say the scalar field of BLS12-381.

## Version

Current HEAD in arkworks-rs/curves (d1ced15cc28b76c3496502a5b0408b1e48eb4c5d).

**Comment by weikengchen** [comment] 2022-01-01 10:39
This appears to have been fixed by @zhenfeizhang (https://github.com/arkworks-rs/curves/commit/129795aa4cb76a2cde1fa96544258c359c9252ce), but the problem is that we haven't released a new version, so that docs.rs has the previous version's one.

It would be fixed once we upgrade the version. The refactoring about the curve parameters is done. It may be coming soon.

**Comment by weikengchen** [comment] 2022-01-11 18:38
Let me close this issue. I will ask on next arkworks meeting about the schedule of next release.

**Closed by weikengchen** 2022-01-11 18:38 UTC
