### ISSUE TITLE
cargo build fails

### ISSUE THREAD

**Issue by StefanosChaliasos** [arkworks-rs/curves#164] opened 2023-07-04 17:25 UTC
∂

## Summary of Bug

When trying to build the project, building fails with 10 errors.

## Version

master branch

## Steps to Reproduce

```
cargo build
```

Result:

```
error: unused import: `Field`
 --> mnt4_298/src/curves/g2.rs:6:14
  |
6 | use ark_ff::{Field, MontFp};
  |              ^^^^^
  |
note: the lint level is defined here
 --> mnt4_298/src/lib.rs:4:5
  |
4 |     unused,
  |     ^^^^^^
  = note: `#[deny(unused_imports)]` implied by `#[deny(unused)]`

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
  --> secp256k1/src/curves/mod.rs:32:29
   |
32 |     const COEFF_A: Fq = Fq::ZERO;
   |                             ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 4>, 4>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error: unused import: `Field`
 --> bn254/src/curves/g2.rs:5:14
  |
5 | use ark_ff::{Field, MontFp, Zero};
  |              ^^^^^
  |
note: the lint level is defined here
 --> bn254/src/lib.rs:4:5
  |
4 |     unused,
  |     ^^^^^^
  = note: `#[deny(unused_imports)]` implied by `#[deny(unused)]`

error[E0432]: unresolved import `ark_ec::Group`
 --> bls12_381/src/curves/g1.rs:7:17
  |
7 |     AffineRepr, Group,
  |                 ^^^^^ no `Group` in the root

error[E0432]: unresolved import `ark_ec::Group`
 --> bls12_381/src/curves/g2.rs:9:29
  |
9 |     AffineRepr, CurveGroup, Group,
  |                             ^^^^^ no `Group` in the root

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
  --> pallas/src/curves/mod.rs:31:29
   |
31 |     const COEFF_A: Fq = Fq::ZERO;
   |                             ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 4>, 4>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error: unused import: `Field`
 --> bls12_381/src/curves/g1.rs:9:14
  |
9 | use ark_ff::{Field, MontFp, PrimeField, Zero};
  |              ^^^^^
  |
note: the lint level is defined here
 --> bls12_381/src/lib.rs:4:5
  |
4 |     unused,
  |     ^^^^^^
  = note: `#[deny(unused_imports)]` implied by `#[deny(unused)]`

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
  --> mnt4_298/src/curves/g2.rs:55:13
   |
55 |         Fq::ZERO,
   |             ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 5>, 5>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
  --> mnt4_298/src/curves/mod.rs:22:37
   |
22 |     const TWIST: Fq2 = Fq2::new(Fq::ZERO, Fq::ONE);
   |                                     ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 5>, 5>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
  --> mnt4_298/src/curves/mod.rs:29:69
   |
29 |     const TWIST_COEFF_A: Fq2 = Fq2::new(G1_COEFF_A_NON_RESIDUE, Fq::ZERO);
   |                                                                     ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 5>, 5>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `ark-secp256k1` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `ark-pallas` due to previous error
error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
  --> bn254/src/curves/g1.rs:27:29
   |
27 |     const COEFF_A: Fq = Fq::ZERO;
   |                             ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 4>, 4>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error[E0599]: no associated item named `ZERO` found for struct `QuadExtField` in the current scope
  --> bn254/src/curves/g2.rs:35:31
   |
35 |     const COEFF_A: Fq2 = Fq2::ZERO;
   |                               ^^^^ associated item not found in `QuadExtField<Fp2ConfigWrapper<fq2::Fq2Config>>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error: unused import: `Field`
 --> mnt4_753/src/curves/g2.rs:6:14
  |
6 | use ark_ff::{Field, MontFp};
  |              ^^^^^
  |
note: the lint level is defined here
 --> mnt4_753/src/lib.rs:4:5
  |
4 |     unused,
  |     ^^^^^^
  = note: `#[deny(unused_imports)]` implied by `#[deny(unused)]`

error[E0432]: unresolved import `ark_ec::Group`
 --> bls12_377/src/curves/g2.rs:7:29
  |
7 |     AffineRepr, CurveGroup, Group,
  |                             ^^^^^ no `Group` in the root

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
  --> mnt4_298/src/fields/fq4.rs:15:42
   |
15 |     const NONRESIDUE: Fq2 = Fq2::new(Fq::ZERO, Fq::ONE);
   |                                          ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 5>, 5>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
   --> bls12_381/src/curves/g2.rs:209:9
    |
209 |     Fq::ZERO,
    |         ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 6>, 6>`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use ark_ec::AdditiveGroup;
    |

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
   --> bls12_381/src/curves/g2.rs:226:9
    |
226 |     Fq::ZERO
    |         ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 6>, 6>`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use ark_ec::AdditiveGroup;
    |

error: could not compile `ark-mnt4-298` due to 5 previous errors
error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
  --> bls12_381/src/curves/g1.rs:42:29
   |
42 |     const COEFF_A: Fq = Fq::ZERO;
   |                             ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 6>, 6>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error[E0599]: no method named `mul_bigint` found for struct `ark_ec::short_weierstrass::Projective` in the current scope
  --> bls12_381/src/curves/g1.rs:69:49
   |
69 |         let minus_x_squared_times_p = x_times_p.mul_bigint(crate::Config::X).neg();
   |                                                 ^^^^^^^^^^ method not found in `ark_ec::short_weierstrass::Projective<curves::g1::Config>`
   |
  ::: /Users/user/.cargo/git/checkouts/algebra-7e23afa68841b66e/c015ea3/ec/src/lib.rs:60:8
   |
60 |     fn mul_bigint(&self, other: impl AsRef<[u64]>) -> Self;
   |        ---------- the method is available for `ark_ec::short_weierstrass::Projective<curves::g1::Config>` here
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::PrimeGroup;
   |

error[E0599]: no method named `double` found for struct `ark_ec::short_weierstrass::Projective` in the current scope
   --> bls12_381/src/curves/g2.rs:101:69
    |
101 |         let mut psi2_p2 = double_p_power_endomorphism(&p_projective.double());
    |                                                                     ^^^^^^ method not found in `ark_ec::short_weierstrass::Projective<curves::g2::Config>`
    |
   ::: /Users/user/.cargo/git/checkouts/algebra-7e23afa68841b66e/c015ea3/ff/src/fields/mod.rs:93:8
    |
93  |     fn double(&self) -> Self {
    |        ------ the method is available for `ark_ec::short_weierstrass::Projective<curves::g2::Config>` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use ark_ec::AdditiveGroup;
    |

error[E0599]: no method named `mul_bigint` found for struct `ark_ec::short_weierstrass::Projective` in the current scope
   --> bls12_381/src/curves/g2.rs:109:21
    |
109 |         tmp2 = tmp2.mul_bigint(x).neg();
    |                     ^^^^^^^^^^ method not found in `ark_ec::short_weierstrass::Projective<curves::g2::Config>`
    |
   ::: /Users/user/.cargo/git/checkouts/algebra-7e23afa68841b66e/c015ea3/ec/src/lib.rs:60:8
    |
60  |     fn mul_bigint(&self, other: impl AsRef<[u64]>) -> Self;
    |        ---------- the method is available for `ark_ec::short_weierstrass::Projective<curves::g2::Config>` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use ark_ec::PrimeGroup;
    |

error: could not compile `ark-bn254` due to 3 previous errors
error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
  --> mnt4_753/src/curves/g2.rs:62:13
   |
62 |         Fq::ZERO,
   |             ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 12>, 12>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
  --> mnt4_753/src/curves/mod.rs:25:54
   |
25 |     const TWIST: Fp2<Self::Fp2Config> = Fp2::new(Fq::ZERO, Fq::ONE);
   |                                                      ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 12>, 12>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
  --> mnt4_753/src/curves/mod.rs:32:86
   |
32 |     const TWIST_COEFF_A: Fp2<Self::Fp2Config> = Fp2::new(G1_COEFF_A_NON_RESIDUE, Fq::ZERO);
   |                                                                                      ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 12>, 12>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
   --> bls12_377/src/curves/g2.rs:125:9
    |
125 |     Fq::ZERO,
    |         ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 6>, 6>`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use ark_ec::AdditiveGroup;
    |

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
   --> bls12_377/src/curves/g2.rs:132:13
    |
132 |         Fq::ZERO,
    |             ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 6>, 6>`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use ark_ec::AdditiveGroup;
    |

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
   --> bls12_377/src/curves/g2.rs:138:13
    |
138 |         Fq::ZERO
    |             ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 6>, 6>`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use ark_ec::AdditiveGroup;
    |

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
  --> bls12_377/src/curves/g1.rs:39:29
   |
39 |     const COEFF_A: Fq = Fq::ZERO;
   |                             ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 6>, 6>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
  --> bls12_377/src/curves/g2.rs:58:13
   |
58 |         Fq::ZERO,
   |             ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 6>, 6>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error[E0599]: no method named `double` found for struct `ark_ec::short_weierstrass::Projective` in the current scope
  --> bls12_377/src/curves/g2.rs:83:69
   |
83 |         let mut psi2_p2 = double_p_power_endomorphism(&p_projective.double());
   |                                                                     ^^^^^^ method not found in `ark_ec::short_weierstrass::Projective<curves::g2::Config>`
   |
  ::: /Users/user/.cargo/git/checkouts/algebra-7e23afa68841b66e/c015ea3/ff/src/fields/mod.rs:93:8
   |
93 |     fn double(&self) -> Self {
   |        ------ the method is available for `ark_ec::short_weierstrass::Projective<curves::g2::Config>` here
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error[E0599]: no method named `mul_bigint` found for struct `ark_ec::short_weierstrass::Projective` in the current scope
  --> bls12_377/src/curves/g2.rs:91:21
   |
91 |         tmp2 = tmp2.mul_bigint(x);
   |                     ^^^^^^^^^^ method not found in `ark_ec::short_weierstrass::Projective<curves::g2::Config>`
   |
  ::: /Users/user/.cargo/git/checkouts/algebra-7e23afa68841b66e/c015ea3/ec/src/lib.rs:60:8
   |
60 |     fn mul_bigint(&self, other: impl AsRef<[u64]>) -> Self;
   |        ---------- the method is available for `ark_ec::short_weierstrass::Projective<curves::g2::Config>` here
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::PrimeGroup;
   |

error: unused import: `ops::Neg`
  --> bls12_381/src/curves/g1.rs:11:15
   |
11 | use ark_std::{ops::Neg, One};
   |               ^^^^^^^^

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `ark-bls12-381` due to 10 previous errors
error: could not compile `ark-bls12-377` due to 8 previous errors
error[E0599]: no associated item named `ZERO` found for struct `ark_ff::Fp` in the current scope
  --> mnt4_753/src/fields/fq4.rs:15:42
   |
15 |     const NONRESIDUE: Fq2 = Fq2::new(Fq::ZERO, Fq::ONE);
   |                                          ^^^^ associated item not found in `ark_ff::Fp<ark_ff::MontBackend<FqConfig, 12>, 12>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ark_ec::AdditiveGroup;
   |

error: could not compile `ark-mnt4-753` due to 5 previous errors
error[E0432]: unresolved import `ark_ec::Group`
 --> /Users/user/.cargo/git/checkouts/r1cs-std-264917fec42faaac/f85e92d/src/groups/curves/short_weierstrass/non_zero_affine.rs:2:5
  |
2 | use ark_ec::Group;
  |     ^^^^^^^^^^^^^ no `Group` in the root

error[E0432]: unresolved import `ark_ec::Group`
 --> /Users/user/.cargo/git/checkouts/r1cs-std-264917fec42faaac/f85e92d/src/groups/curves/twisted_edwards/mod.rs:6:29
  |
6 |     AffineRepr, CurveGroup, Group,
  |                             ^^^^^ no `Group` in the root

error[E0599]: no method named `double` found for associated type `<P as Bls12Config>::Fp` in the current scope
   --> /Users/user/.cargo/git/checkouts/r1cs-std-264917fec42faaac/f85e92d/src/groups/curves/short_weierstrass/bls12/mod.rs:202:36
    |
202 |         let two_inv = P::Fp::one().double().inverse().unwrap();
    |                                    ^^^^^^ method not found in `<P as Bls12Config>::Fp`
    |
   ::: /Users/user/.cargo/git/checkouts/algebra-7e23afa68841b66e/c015ea3/ff/src/fields/mod.rs:93:8
    |
93  |     fn double(&self) -> Self {
    |        ------ the method is available for `<P as Bls12Config>::Fp` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use crate::ark_ff::AdditiveGroup;
    |

error[E0599]: no method named `double` found for struct `ark_ec::short_weierstrass::Projective` in the current scope
  --> /Users/user/.cargo/git/checkouts/r1cs-std-264917fec42faaac/f85e92d/src/groups/curves/short_weierstrass/non_zero_affine.rs:75:18
   |
75 |                 .double()
   |                  ^^^^^^ method not found in `ark_ec::short_weierstrass::Projective<P>`
   |
  ::: /Users/user/.cargo/git/checkouts/algebra-7e23afa68841b66e/c015ea3/ff/src/fields/mod.rs:93:8
   |
93 |     fn double(&self) -> Self {
   |        ------ the method is available for `ark_ec::short_weierstrass::Projective<P>` here
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use crate::ark_ff::AdditiveGroup;
   |

error[E0599]: no method named `double` found for associated type `<P as CurveConfig>::BaseField` in the current scope
   --> /Users/user/.cargo/git/checkouts/r1cs-std-264917fec42faaac/f85e92d/src/groups/curves/short_weierstrass/mod.rs:248:34
    |
248 |         let three_b = P::COEFF_B.double() + &P::COEFF_B;
    |                                  ^^^^^^ method not found in `<P as CurveConfig>::BaseField`
    |
   ::: /Users/user/.cargo/git/checkouts/algebra-7e23afa68841b66e/c015ea3/ff/src/fields/mod.rs:93:8
    |
93  |     fn double(&self) -> Self {
    |        ------ the method is available for `<P as CurveConfig>::BaseField` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use crate::ark_ff::AdditiveGroup;
    |

error[E0599]: no method named `double` found for associated type `<P as CurveConfig>::BaseField` in the current scope
   --> /Users/user/.cargo/git/checkouts/r1cs-std-264917fec42faaac/f85e92d/src/groups/curves/short_weierstrass/mod.rs:462:34
    |
462 |         let three_b = P::COEFF_B.double() + &P::COEFF_B;
    |                                  ^^^^^^ method not found in `<P as CurveConfig>::BaseField`
    |
   ::: /Users/user/.cargo/git/checkouts/algebra-7e23afa68841b66e/c015ea3/ff/src/fields/mod.rs:93:8
    |
93  |     fn double(&self) -> Self {
    |        ------ the method is available for `<P as CurveConfig>::BaseField` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use crate::ark_ff::AdditiveGroup;
    |

error[E0599]: no method named `double` found for associated type `<P as CurveConfig>::BaseField` in the current scope
   --> /Users/user/.cargo/git/checkouts/r1cs-std-264917fec42faaac/f85e92d/src/groups/curves/short_weierstrass/mod.rs:636:38
    |
636 |             let three_b = P::COEFF_B.double() + &P::COEFF_B;
    |                                      ^^^^^^ method not found in `<P as CurveConfig>::BaseField`
    |
   ::: /Users/user/.cargo/git/checkouts/algebra-7e23afa68841b66e/c015ea3/ff/src/fields/mod.rs:93:8
    |
93  |     fn double(&self) -> Self {
    |        ------ the method is available for `<P as CurveConfig>::BaseField` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use crate::ark_ff::AdditiveGroup;
    |

error[E0599]: no method named `double` found for struct `ark_ec::twisted_edwards::Projective` in the current scope
   --> /Users/user/.cargo/git/checkouts/r1cs-std-264917fec42faaac/f85e92d/src/groups/curves/twisted_edwards/mod.rs:482:42
    |
482 |             *self = Self::constant(value.double());
    |                                          ^^^^^^ method not found in `ark_ec::twisted_edwards::Projective<P>`
    |
   ::: /Users/user/.cargo/git/checkouts/algebra-7e23afa68841b66e/c015ea3/ff/src/fields/mod.rs:93:8
    |
93  |     fn double(&self) -> Self {
    |        ------ the method is available for `ark_ec::twisted_edwards::Projective<P>` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use crate::ark_ff::AdditiveGroup;
    |

error[E0599]: no method named `double` found for associated type `<P as CurveConfig>::BaseField` in the current scope
   --> /Users/user/.cargo/git/checkouts/r1cs-std-264917fec42faaac/f85e92d/src/groups/curves/twisted_edwards/mod.rs:496:38
    |
496 |                 let t0 = xy.value()?.double();
    |                                      ^^^^^^ method not found in `<P as CurveConfig>::BaseField`
    |
   ::: /Users/user/.cargo/git/checkouts/algebra-7e23afa68841b66e/c015ea3/ff/src/fields/mod.rs:93:8
    |
93  |     fn double(&self) -> Self {
    |        ------ the method is available for `<P as CurveConfig>::BaseField` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use crate::ark_ff::AdditiveGroup;
    |

error[E0599]: no method named `double` found for associated type `<P as CurveConfig>::BaseField` in the current scope
   --> /Users/user/.cargo/git/checkouts/r1cs-std-264917fec42faaac/f85e92d/src/groups/curves/twisted_edwards/mod.rs:506:43
    |
506 |             let two = P::BaseField::one().double();
    |                                           ^^^^^^ method not found in `<P as CurveConfig>::BaseField`
    |
   ::: /Users/user/.cargo/git/checkouts/algebra-7e23afa68841b66e/c015ea3/ff/src/fields/mod.rs:93:8
    |
93  |     fn double(&self) -> Self {
    |        ------ the method is available for `<P as CurveConfig>::BaseField` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use crate::ark_ff::AdditiveGroup;
    |

error: could not compile `ark-r1cs-std` due to 10 previous errors
```

**Comment by weikengchen** [comment] 2023-07-04 18:20
Can you do `cargo update`? @StefanosChaliasos  

The main branch uses some repos by the GitHub references, and therefore versions do not automatically propagate.

**Comment by weikengchen** [comment] 2023-07-04 18:21
Actually forget about that, I think the issue is with the latest algebra. Let me do some things...

**Comment by mmagician** [comment] 2023-09-03 11:54
@StefanosChaliasos This should be fixed now - let us know in case you're still running into any issues.

**Closed by mmagician** 2023-09-03 11:54 UTC
